// <auto-generated />
using System;
using Data.Concretes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApi.Migrations.SecondDb
{
    [DbContext(typeof(SecondDbContext))]
    [Migration("20220317020251_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastUpdateUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            CreateDate = new DateTime(2022, 3, 17, 5, 2, 50, 530, DateTimeKind.Local).AddTicks(500),
                            CreateUser = "Admin",
                            Email = "ahmet.gunduz@xyz.com",
                            FirstName = "Ahmet",
                            LastName = "Gündüz",
                            LastUpdate = new DateTime(2022, 3, 17, 5, 2, 50, 546, DateTimeKind.Local).AddTicks(1970),
                            LastUpdateUser = "Admin",
                            PhoneNumber = "123548"
                        },
                        new
                        {
                            Id = 2,
                            City = "Ankara",
                            CreateDate = new DateTime(2022, 3, 17, 5, 2, 50, 546, DateTimeKind.Local).AddTicks(9900),
                            CreateUser = "Admin",
                            Email = "mustafa.yilmaz@xyz.com",
                            FirstName = "Mustafa",
                            LastName = "Yılmaz",
                            LastUpdate = new DateTime(2022, 3, 17, 5, 2, 50, 547, DateTimeKind.Local).AddTicks(160),
                            LastUpdateUser = "Admin",
                            PhoneNumber = "2322323"
                        },
                        new
                        {
                            Id = 3,
                            City = "İzmir",
                            CreateDate = new DateTime(2022, 3, 17, 5, 2, 50, 547, DateTimeKind.Local).AddTicks(990),
                            CreateUser = "Admin",
                            Email = "mehmet.gunes@xyz.com",
                            FirstName = "Mehmet",
                            LastName = "Güneş",
                            LastUpdate = new DateTime(2022, 3, 17, 5, 2, 50, 547, DateTimeKind.Local).AddTicks(1000),
                            LastUpdateUser = "Admin",
                            PhoneNumber = "2323"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
